language: php
php:
  - 7.1.9

cache:
  directories:
    - $HOME/.composer/caches/files
    - ./bin/.phpunit

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak

install:
  - composer install
  - php bin/phpunit