<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAsmNqUI\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAsmNqUI/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerAsmNqUI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerAsmNqUI\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerAsmNqUI\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'AsmNqUI',
    'container.build_id' => '741b8b24',
    'container.build_time' => 1549531583,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAsmNqUI');
