<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZQin3iH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZQin3iH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZQin3iH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZQin3iH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZQin3iH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZQin3iH',
    'container.build_id' => '56b08fc6',
    'container.build_time' => 1549533134,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZQin3iH');
